### ISSUE TITLE
rutha-ionic v0.3.0 - con Gulp

### ISSUE THREAD

**Issue by molekilla** [molekilla/rutha-ionic#1]
@rbonillajr @bradleySuira

usemos este fork como base 
https://github.com/bradleySuira/rutha-ionic/commit/eaacc46691e7530e59a7b00b38f071fae39b4413

@edgarSucre fyi!

**Comment by matheo** [comment]
Hola Rogelio
Aquí en Colombia estamos comenzando con Hapi + ionic y encontramos a Rutha en la lista de recursos. Quisiéramos saber si hay progresos recientes, ya que las versiones que se estan usando en Rutha son de varios meses atrás.
Saludos y gracias por el ejemplo!

**Comment by molekilla** [comment]
Hola Mateo

Actualmente estamos con ng-panama creando 2 forks, un stack con Gulp que lo
lidera @rbonillajr y otro con Typescript. La idea es:
- rutha-ionic que use SASS y Gulp
- forkear rutha a rutha2 que seria SASS, Gulp y Typescript

rutha 1.0 esta estable de nuestro, lo usamos en
https://demo.autentifactor.com y para otros dos desarollos, uno de seguros
online y otro de banca movil.

De todas maneras si te interesa colaborar bienvenido sea, yo estare el 15
de Oct en el jsconf en Medellin y si estas por aya podemos hablar de Hapi.

Saludos
Rogelio

**Comment by rbonillajr** [comment]
Hola @matheo 

cuentanos un poco que quieres hacer o a que se dedican y si pues podemos ayudarles con el soporte de Rutha-ionic.

actualmente estamos trabajando en varias cosas como te menciono @molekilla 

Saludos,

Rene.

**Comment by matheo** [comment]
Estamos organizando un stack con Hapi + Ionic + Massive.js (Postgres), y ojalá se pueda integrar Angular Material (veo que en el demo hacen algo con kendo).

Queremos programar con TypeScript también, por lo que estamos documentándonos en buenas prácticas y la organización necesaria para tener un proyecto mantenible y escalable.

Gulp también parece la herramienta más adecuada con node, y bueno, esa es la idea general, luego veremos el trabajo con SASS también.

Comenzaremos con una pequeña aplicación SPA que necesitamos con cierta urgencia por aquí, y esperamos sacar aprendizajes para mejorar el esqueleto para proyectos futuros.

A ver si en un mes tenemos la alegría de conocernos en persona! :)

**Comment by molekilla** [comment]
Excelente, cualquier cosa nos avisas.

**Comment by molekilla** [comment]
Closed
https://github.com/molekilla/rutha-ionic/pull/3 @edgarSucre @matheo @rbonillajr @bradleySuira
